"""empty message

Revision ID: 71d688484cd1
Revises: 1ba6cfaf0ace
Create Date: 2021-03-31 20:30:21.801480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d688484cd1'
down_revision = '1ba6cfaf0ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnes',
    sa.Column('cnpj', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.cnpj'], ),
    sa.PrimaryKeyConstraint('cnpj'),
    sa.UniqueConstraint('cnpj')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cnes')
    # ### end Alembic commands ###
