"""empty message

Revision ID: 910c1eed7edd
Revises: 71d688484cd1
Create Date: 2021-03-31 21:20:33.476400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910c1eed7edd'
down_revision = '71d688484cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upa',
    sa.Column('cnes', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.cnpj'], ),
    sa.PrimaryKeyConstraint('cnes'),
    sa.UniqueConstraint('cnes')
    )
    op.drop_table('cnes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnes',
    sa.Column('cnpj', sa.VARCHAR(length=120), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('country_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.cnpj'], ),
    sa.PrimaryKeyConstraint('cnpj'),
    sa.UniqueConstraint('cnpj')
    )
    op.drop_table('upa')
    # ### end Alembic commands ###
